exec.out: main.o trianguloSierpinski.o alfombraSierpinski.o renderer.o copoKoch.o cuadradosSierpinski.o decagonoSierpinski.o heptagonoSierpinski.o hexagonoSierpinski.o nonagonoSierpinski.o octagonoSierpinski.o pentagonoSierpinski.o decagonoSierpinski.o
	g++ *.o -o exec.out -lsfml-graphics -lsfml-window -lsfml-system -std=c++11
	
main.o: main.cpp
	g++ -std=c++11 -c main.cpp

copoKoch.o: copoKoch.cpp Headers/copoKoch.h
	g++ -std=c++11 -c copoKoch.cpp

alfombraSierpinski.o: alfombraSierpinski.cpp Headers/alfombraSierpinski.h
	g++ -std=c++11 -c alfombraSierpinski.cpp

trianguloSierpinski.o: trianguloSierpinski.cpp Headers/trianguloSierpinski.h
	g++ -std=c++11 -c trianguloSierpinski.cpp

renderer.o: renderer.cpp Headers/renderer.h
	g++ -std=c++11 -c renderer.cpp
	
cuadradoSierpinski.o: cuadradoSierpinski.cpp Headers/cuadradoSierpinski.h
	g++ -std=c++11 -c cuadradoSierpinski.cpp

decagonoSierpinski.o: decagonoSierpinski.cpp Headers/decagonoSierpinski.h
	g++ -std=c++11 -c decagonoSierpinski.cpp

heptagonoSierpinski.o: heptagonoSierpinski.cpp Headers/heptagonoSierpinski.h
	g++ -std=c++11 -c heptagonoSierpinski.cpp

hexagonoSierpinski.o: hexagonoSierpinski.cpp Headers/hexagonoSierpinski.h
	g++ -std=c++11 -c hexagonoSierpinski.cpp

nonagonoSierpinski.o: nonagonoSierpinski.cpp Headers/nonagonoSierpinski.h
	g++ -std=c++11 -c nonagonoSierpinski.cpp

octagonoSierpinski.o: octagonoSierpinski.cpp Headers/octagonoSierpinski.h
	g++ -std=c++11 -c octagonoSierpinski.cpp

pentagonoSierpinski.o: pentagonoSierpinski.cpp Headers/pentagonoSierpinski.h
	g++ -std=c++11 -c pentagonoSierpinski.cpp

decagonoSierpinski.o: decagonoSierpinski.cpp Headers/decagonoSierpinski.h
	g++ -std=c++11 -c decagonoSierpinski.cpp
